application:
  port: 3000
  name: "User Service"
  version: "1.0.0"
  environment: "development"
  log_level: "debug"
  jwt:
    secret: "secret"
    expiration: 3600
    issuer: "user-service"
  database:
    host: "localhost"
    port: 5432
    user: "user"
    password: "12345678"
    dbname: "db"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
